version: "3.6"

services:
  exchange_stream_recorder_rust:
    build:
      context: .
      dockerfile: Dockerfile.exchange_stream_recorder_rust
    image: exchange_stream_recorder_rust
    restart: always
    ports:
      - 8000:8000
    environment:
      - APP_KEY=${APP_KEY}
      - SSOID=${SSOID}
      - MARKET_ID=${MARKET_ID}
      - MONGO_CONN="mongodb://root:password123@mongodb-primary_1:27017/"
    depends_on:
      - mongo-express

  # Mongo UI
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 9081:8081
    depends_on:
      - mongodb-primary
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
      ME_CONFIG_MONGODB_SERVER: mongodb-primary
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      
  # MongoDB
  mongodb-primary:
    image: "bitnami/mongodb:4.0"
    ports:
      - 27017:27017
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_ROOT_PASSWORD=password123
    volumes:
      - "mongodb_master_data:/bitnami"

volumes:
  mongodb_master_data:
    driver: local